export { default as BannerShop } from './components/BannerShop/BannerShop'
export { default as BestFood} from './components/BestFood/BestFood'
export { default as Comment} from './components/Comment/Comment'
export { default as Delivery } from './components/Delivery/Delivery'
export { default as Footer } from './components/Footer/Footer'
export { default as Header } from './components/Header/Header'
export { default as Information} from './components/Information/Information'
export { default as Ingredients} from './components/Ingredients/Ingredients'
export { default as Login } from './components/Login/Login'
export { default as ProductShop } from './components/ProductShop/ProductShop'
export { default as QualityProducts } from './components/QualityProducts/QualityProducts'
export { default as SearchShop } from './components/SearchShop/SearchShop'
export { default as Slidebar } from './components/Slidebar/Slidebar'
export { default as Slider } from './components/Slider/Slider'
export { default as Working } from './components/Working/Working'